apiVersion: v1
kind: ServiceAccount
metadata:
  name: edge-connect-hpa-reader
  namespace: dynatrace
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: edge-connect-hpa-reader
rules:
  - apiGroups: ["autoscaling"]
    resources: ["horizontalpodautoscalers"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: edge-connect-hpa-reader
roleRef:
  kind: ClusterRole
  name: edge-connect-hpa-reader
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: edge-connect-hpa-reader
    namespace: dynatrace
---
apiVersion: dynatrace.com/v1alpha1
kind: EdgeConnect
metadata:
  name: bookish-enigma-pjw7w4x9r765c756j
  namespace: dynatrace
spec:
  apiServer: dhg95339.sprint.apps.dynatracelabs.com
  serviceAccountName: edge-connect-hpa-reader
  oauth:
    provisioner: true
    clientSecret: edge-connect-bookish-enigma-pjw7w4x9r765c756j-credentials
    endpoint: https://sso-sprint.dynatracelabs.com/sso/oauth2/token
    resource: "urn:dtenvironment:dhg95339"
  kubernetesAutomation:
    enabled: true